module.exports = {
  KMS: {
    API_VERSION: '2014-11-01',
    DEFAULT_ENCRYPTION_SPEC: 'AES_256',
  },
  ENCRYPTION: {
    DEFAULT_INPUT_ENCODING: 'utf8',
    DEFAULT_OUTPUT_ENCODING: 'base64',
    DEFAULT_ENCRYPTION_SPEC: 'aes256',
  },
  DEFAULT_BUFFERS_ENCODING: 'base64',
};
